from exceptions import EmptyStackException
from stack import Stack
import unittest


class TestStack(unittest.TestCase):
    def testSomething(self):
        x = 2 + 2
        self.assertTrue(4, x)


if __name__ == '__main__':
    unittest.main()
